### ISSUE TITLE
To-do before Jan 1st

### ISSUE THREAD

**Issue by saisundu** [saisundu/grade-10-igcse-past-papers#21]
- [ ] Maths paper 2 past papers since 2020 -  2023
- [ ] Maths paper 4 past papers since 2017 -  2023
- [ ] Environmental Management  paper 1 past papers since 2017 - 2023
- [ ] Environmental Management  paper  2 past papers since 2017 - 2023
